site_name: 'KB dbalucas'

plugins: 
  - search
  - markdownextradata

repo_name: 'KB_dbalucas'
site_url: https://dbalucas.github.io/KB_dbalucas
repo_url: https://github.com/dbalucas/KB_dbalucas

nav:
  - Home: 'README.md'
  - Usage of GIT: 
    - 'Git Rules': 'git_howtos/git_rules.md'
  - Troubleshooting:
    - 'Failed connections': 'troubleshooting/failed_connections.md'
    - 'Server uptime': 'troubleshooting/server_uptime.md'
  - About: 'about.md'
  - License: 'license.md'

theme:
  name: 'material'
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

  hljs_languages:
      - yaml
      - pythong
      - pgsql
  prev_next_buttons_location: both
  local: en
  font: false
