nav:
  - Home: 
    - 'Home': 'README.md'
  - Troubleshooting:
    - 'Failed connections': 'troubleshooting/failed_connections.md'
    - 'Server uptime': 'troubleshooting/server_uptime.md'
  - About: 'about.md'
  - License: 'license.md'


theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
      - yaml
      - pythong
      - pgsql
  prev_next_buttons_location: both
  local: en

site_name: 'HowTo be a PostgreSQL DBA'
site_url: https://dbablog.eu/HowToDBA
repo_url: https://github.com/dbalucas/HowTo_DBA
